// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE


function createClient(domain, httpRequest) {
  return {
          getUsers: (function (param) {
              return Promise.resolve(/* array */[]);
            })
        };
}

var getUsersPath = "/users";

export {
  getUsersPath ,
  createClient ,
  
}
/* No side effect */
