// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE


function createAtlasClient(connection) {
  var getUsers = function (param) {
    return Promise.resolve(/* array */[]);
  };
  return /* record */[/* getUsers */getUsers];
}

export {
  createAtlasClient ,
  
}
/* No side effect */
